### ISSUE TITLE
Readme feedback

### ISSUE THREAD

**Issue by umaar** [dojo/stores#155]
Here are my notes I made from reading `https://github.com/dojo/stores`. A bunch of these notes are API related questions, which are less about the readme, and more about the package itself. Feel free to ignore!

1. The Github description url points to http://dojo.io - is there a tutorial or something we could use instead?

2. Can we make the description more descriptive? Right now it's "Dojo 2 - data stores"

3. Can this warning (alpha warning) be removed?:

>WARNING This is alpha software. It is not yet production ready, so you should use at your own risk.

4. Before the docs continued, would be nice as a reader to understand when would I _not_ want to use this? Some advantages are listed, but no disadvantages.

5. Might be nicer to improve the code block here: https://github.com/dojo/stores#operations

Transform this:

```js
const operations = [
    { op: OperationType.ADD, path: new JsonPointer('/foo'), value: 'foo' },
    { op: OperationType.REPLACE, path: new JsonPointer('/bar'), value: 'bar' },
    { op: OperationType.REMOVE, path: new JsonPointer('/qux') },
];
```

Into this?

```js
const operations = [{
    op: OperationType.ADD,
    path: new JsonPointer('/foo'),
    value: 'foo'
}, {
    op: OperationType.REPLACE,
    path: new JsonPointer('/bar'),
    value: 'bar'
}, {
    op: OperationType.REMOVE,
    path: new JsonPointer('/qux')
}];
```

Also in the original code block there is a trailing comma in the last object in the array.

6. Looking at the code block in the Commands section, I'm not entirely sure what the variables `JsonPointer` and `OperationType` are/where they came from.

7.
> These function accept

should be "These functions accept"

8.
> A Command, or the CommandRequest argument to it

To what?

9.
> Important: Access to state root is not permitted and will throw an error

Could be worth explaining why?

10. For code like this:

```js
replace(at(path('todos'), index), { ...todos[index], loading: false, id: data.uuid })
```

I think it'd be nicer if it were formatted with more line breaks.

11. This may be a naive question, but had an API design question: on first glance, for some of these functions like `at`, `replace` `get`, is it possible to replace them with vanilla JS techniques? E.g. the code above reminds me of:

```js
const newObject = {
    ...oldObject,
    {
        ...todos
    }
}
```

Would it make sense to promote code like that?

12.
>  The result object contains the payload passed

For over two items, I would use a bullet pointed list as it's easier to consume.

```
The result object contains the following properties:

- The payload passed to the process
-
-
```

13. API Design question:

```js
const addTodoProcess = createProcess([ addTodoCommand, calculateCountCommand ], { callback: addTodoProcessCallback });
```

How about instead of a callback, it returned a promise so you could could:

```js
const addTodoProcess = createProcess([ addTodoCommand, calculateCountCommand ])
const {error, result} = await addToProcess(store)(payload);
```

14.
API Design question on the `initial state` section:

```js
// Command that creates the basic initial state
const initialStateCommand = createCommand({ path }) => {
    return [
        add(path('todos'), []),
        add(path('currentTodo'), ''),
        add(path('activeCount'), 0),
        add(path('completedCount'), 0)
    ]);
}
```

I find the API to be a little odd (but most likely because I don't understand something), any chance we could deal with regular JS objects here? I think that'd be cleaner and more intutive, e.g.

```js
// Command that creates the basic initial state
const initialStateCommand = createCommand({ path }) => {
    return {
        todos: [],
        currentTodo: '',
        activeCount: 0,
        completedCount: 0
    };
}
```

I feel having to make two function calls per property in this manner is extra congitive overhead which could deter someone in using this package? But again these are defo my own personal thoughts, and it's probably because I don't understand something!

15. There's a code snippet with this:

```js
// creates the store, initializes the state and runs the `getTodosProcess`.
const store = createStore();
```

But it's unclear what `getTodosProcess` is.

16.

> simply register to the stores .on() for a t

Specify, `.on() method`

17. API Design question: yet another thing I'm probably missing, but here:

```js
function addTodoCallback(error, result) {
    if (error) {
        result.undo();
        result.executor(handleAddTodoErrorProcess);
    }
}
```

18. Any reason why `result.executor(handleAddTodoErrorProcess);` must be called instead of calling `handleAddTodoErrorProcess()` directly?

19.

> // running `undeor` will

Typo with `undeor`

20.

> © 2017 JS Foundation. New BSD license.

Can update the year!

**Comment by agubler** [comment]
> 4. Before the docs continued, would be nice as a reader to understand when would I _not_ want to use this? Some advantages are listed, but no disadvantages.

Certainly we can do this. We could explain that not all applications need an application state store, that lifting up state and property passing is a perfectly reasonable pattern.

> 5. Might be nicer to improve the code block here: https://github.com/dojo/stores#operations

> Transform this:

> ```js
> const operations = [
>     { op: OperationType.ADD, path: new JsonPointer('/foo'), value: 'foo' },
>     { op: OperationType.REPLACE, path: new JsonPointer('/bar'), value: 'bar' },
>     { op: OperationType.REMOVE, path: new JsonPointer('/qux') },
> ];
>```

> Into this?

> ```js
> const operations = [{
>     op: OperationType.ADD,
>     path: new JsonPointer('/foo'),
>     value: 'foo'
> }, {
>     op: OperationType.REPLACE,
>     path: new JsonPointer('/bar'),
>     value: 'bar'
> }, {
>     op: OperationType.REMOVE,
>     path: new JsonPointer('/qux')
> }];
> ```

I don't have a real preference either way on this, if the concensus is that it is clearer updating the formatting then I am fine with that. I tend to write inline as long as the length isn't too bad.

> Also in the original code block there is a trailing comma in the last object in the array.

A typo, should remove that!

> 6. Looking at the code block in the Commands section, I'm not entirely sure what the variables `JsonPointer` and `OperationType` are/where they came from.

Did you mean the `Operations` section? If so we should add the imports.

> 7.
> > These function accept

> should be "These functions accept"

Yup!.

> 8.
> > A Command, or the CommandRequest argument to it

> To what?

A very good question, not sure what it is supposed to actually say!

> 9.
> > Important: Access to state root is not permitted and will throw an error

> Could be worth explaining why?

We can do, the main reason is because we don't want consumers treating it as a giant object :)

> 10. For code like this:

> ```js
> replace(at(path('todos'), index), { ...todos[index], loading: false, id: data.uuid })
> ```

> I think it'd be nicer if it were formatted with more line breaks.

As above, if it makes it clearer then I am on board with changing the formatting

> 11. This may be a naive question, but had an API design question: on first glance, for some of these functions like `at`, `replace` `get`, is it possible to replace them with vanilla JS techniques? E.g. the code above reminds me of:

> ```js
> const newObject = {
>    ...oldObject,
>    {
>        ...todos
>    }
>}
>```

The `at` and `path` APIs are designed to provide typings for the state and `get` and `replace` use JSON patch under the hood so they cannot be replaced by the above code. This is the only way to get and modify the state in stores is using JSON patch.

> 12.
> >  The result object contains the payload passed

> For over two items, I would use a bullet pointed list as it's easier to consume.

> ```
> The result object contains the following properties:
> 
> - The payload passed to the process
> -
> -
> ```

Happy for any reformatting to be done!

> 13. API Design question:

> ```js
> const addTodoProcess = createProcess([ addTodoCommand, calculateCountCommand ], { callback: addTodoProcessCallback });
> ```

> How about instead of a callback, it returned a promise so you could could:

> ```js
> const addTodoProcess = createProcess([ addTodoCommand, calculateCountCommand ])
> const {error, result} = await addToProcess(store)(payload);
> ```

This does actually return a `promise` if the `executor` is used directly then it is totally possible to do the above. However in the majority of cases these processes will be called in widget of a user action, at which point the consumer won't want to deal with the next required actions.

> 14.
> API Design question on the `initial state` section:

> ```js
> // Command that creates the basic initial state
> const initialStateCommand = createCommand({ path }) => {
>     return [
>         add(path('todos'), []),
>         add(path('currentTodo'), ''),
>         add(path('activeCount'), 0),
>         add(path('completedCount'), 0)
>     ]);
> }
> ```

> I find the API to be a little odd (but most likely because I don't understand something), any chance we could deal with regular JS objects here? I think that'd be cleaner and more intutive, e.g.

The problem is that stores never exposes the internal state object and is only accessible via the JSON patch mechanisms provided, so it would be misleading to allow the consumer to just dump in an object here also! Additionally there is nothing to say that the state will always be a single object internally in the future so again doesn't make sense to make it feel like it is to the end consumer.

> ```js
> // Command that creates the basic initial state
> const initialStateCommand = createCommand({ path }) => {
>     return {
>         todos: [],
>         currentTodo: '',
>         activeCount: 0,
>         completedCount: 0
>     };
> }
> ```

> I feel having to make two function calls per property in this manner is extra congitive overhead which could deter someone in using this package? But again these are defo my own personal thoughts, and it's probably because I don't understand something!

Unfortunately that doesn't work as stores is only modifiable via JSON patch commands and the `path` function is used to infer the type of that section of state. The `add` wrapper actually generates the JSON patch operation.

> 15. There's a code snippet with this:

> ```js
> // creates the store, initializes the state and runs the `getTodosProcess`.
> const store = createStore();
> ```

> But it's unclear what `getTodosProcess` is.

It's just a process that gets executed (in the code below), happy to clear that up if we can.

> 16.

> > simply register to the stores .on() for a t

> Specify, `.on() method`

Sure!

> 17. API Design question: yet another thing I'm probably missing, but here:

> ```js
> function addTodoCallback(error, result) {
>     if (error) {
>         result.undo();
>         result.executor(handleAddTodoErrorProcess);
>     }
> }
> ```

> 18. Any reason why `result.executor(handleAddTodoErrorProcess);` must be called instead of calling `handleAddTodoErrorProcess()` directly?

because to run a process you need to pass it a `store` instance, which returns an `executor` function that actually performs the `process`, in the callback you do not have access to the `store` but we do provide a runner that does! So even if you had the store it wouldn't just be `handleAddTodoErrorProcess()` it would be:

```ts
handleAddTodoErrorProcess(store)({});
```

**Comment by agubler** [comment]
@umaar Do you mind having a go at updating the README based your observations and my feedback above?
