### ISSUE TITLE
[User Story] Transforming Data

### ISSUE THREAD

**Issue by kitsonk** [dojo/stores#20]
# User Story

A developer, having a set of data, either directly via the Stores API or via the Query API, needs to transform that data from its source shape to another shape(s).  Also, this transformation needs to be able to observe the source data set, so that subsequent changes are propagated through the transformation pipeline.
# Considerations

There are several key factors that need to be considered around the Transformation API:
- _Results_ - Externally, the results of a transformation should have an API surface similar to that of a _read only_ Store.  There should be a way to retrieve meta data about the underlying source of an object that has been transformed so a consumer could go back to the authoritative source to perform a mutation.
- _Multiple Views_ - It is anticipated that many use cases of the transformation will be to take a query or store and transform it into multiple views.  Conceptually, think of a list of todo items, where a developer would need to create widgets (via setting unique widget states) for every todo item returned from a query.  It would need to transform that also to a value of the number of todo items to be displayed in a widget which lists the count of items.
- _Domain Specific Languages_ - There should be available two domain specific languages available to leverage the Transformation API:
  - _Declarative_ - This API should use simple JavaScript objects (POJOs) to provide a declarative way of describing a transformation. This allows the transformation to be easily serialisable to and from JSON. It also allows an easy mechanism for other actors to procedurally generate a transformation and have it executed by the Transformation API.
  - _Functional_ - This should have full functional parity with the declarative syntax but be offered up in chain-able functions, so that a developer can build a transformation incrementally taking advantage of intellisense and robust type validation via TypeScript. There should also be a mechanism to serialise complete functional transformations into the declarative syntax.
- _Offloading and the Query API_ - Implementations of the Transformation API are likely going to be very co-dependent on query implementations to achieve efficient _offloading_.  This is because most server side implementations do not have a strong architectural division between querying and transformation.
- _API functionality_ - While it isn't expected to have a significant superset of the Transformation API for certain implementations, there maybe cause to do so.  This should generally be limited so that the transformation functionality is as "universal" as possible.
- _Interaction with `dojo-app`_ - The Transformation API should work with `dojo-app` to be able to reference more complex objects, like instances of stores, functions, actions and other complex object instances it may need to reference.

**Comment by maier49** [comment]
> A developer, having a set of data, either directly via the Stores API or via the Query API, needs to transform that data from its source shape to another shape(s). 

The current `Query` API was originally intended to be able to handle this kind of operation as well, but I agree it makes sense to separate the two. `Query` currently has two generics that specify the original shape of the data and the resulting shape of the data, but that second generic could be eliminated if a separate transformation API is created to accommodate those needs.

> Also, this transformation needs to be able to observe the source data set, so that subsequent changes are propagated through the transformation pipeline.

Presumably whatever shape the transformation API brings, the providing mixin would be targeting the `createSubcollectionStore` base. If that is the case, the observable mixin will already subscribe to the `source` store's updates and propogate those to any listeners of the child store. 

Currently, there are two distinct states of a subcollection. By default, when a subcollection is from an observable store, it passes updates from the source store to its own observers. It does not filter those through its own query, and the user is expected to call `fetch` to get the latest data from the source store. Potentially, this could be less desirable for a transformed subcollection, as the shape of the data in these updates would be that of the source store and not the subcollection, but the appropriately transformed data could still be retrieved via `fetch`, and this is a more performant default state then automatically applying a transformation to data(especially when that data may not match the child store's query).

The other state is when a subcollection is being tracked. In this case, updates from the parent store are automatically filtered through the appropriate queries and added to the child store, and updates are augmented with appropriate contextualizing information(e.g. information about the items index), etc. This logic could be easily modified to apply whatever transformations are needed to the items before placing them in the child collection as well. One solution to the potential weirdness presented by the un-tracked store scenario would be for any calls to the transformation API to automatically place the store into a tracked state. The transformation mixin could either build off the tracking API, or require the API's presence in whatever store it is being mixed into, if that ability were to be provided by compose.

> Results - Externally, the results of a transformation should have an API surface similar to that of a read only Store. 

I think this makes sense, but I think it might also be useful to provide the ability to optionally specify a transformation back into the shape of the source store. In the case that this transformation is provided the subcollection could have the full store API, and push updates back to its source collection in the same way as other subcollections do now.

> There should be a way to retrieve meta data about the underlying source of an object that has been transformed so a consumer could go back to the authoritative source to perform a mutation

I think this would be accomplished by exposing the `source` property on the `createSubcollectionStore` base.

> Multiple Views - It is anticipated that many use cases of the transformation will be to take a query or store and transform it into multiple views. Conceptually, think of a list of todo items, where a developer would need to create widgets (via setting unique widget states) for every todo item returned from a query. It would need to transform that also to a value of the number of todo items to be displayed in a widget which lists the count of items.

I think this could be accomplished easily enough by making multiple calls to `transform` on the same store, since each call would provide a separate subcollection. The result of a query is currently a collection itself, so unless that changes this would be accomplished already when the `transform` API is provided.

> Domain Specific Languages - There should be available two domain specific languages available to leverage the Transformation API:
> Declarative - This API should use simple JavaScript objects (POJOs) to provide a declarative way of describing a transformation. This allows the transformation to be easily serialisable to and from JSON. It also allows an easy mechanism for other actors to procedurally generate a transformation and have it executed by the Transformation API.

How about a JSON Patch object? E.g.

``` typescript
  [
     { "op": "test", "path": "/a/b/c", "value": "foo" },
     { "op": "remove", "path": "/a/b/c" },
     { "op": "add", "path": "/a/b/c", "value": [ "foo", "bar" ] },
     { "op": "replace", "path": "/a/b/c", "value": 42 },
     { "op": "move", "from": "/a/b/c", "path": "/a/b/d" },
     { "op": "copy", "from": "/a/b/d", "path": "/a/b/e" }
   ]
```

We could duplicate the source object before applying the patch, or alternatively, iterate through the operations like `move` and `copy` and replace them with equivalent add operations, so that the patch could be applied to a fresh object. This isn't necessarily the most expressive syntax though, so maybe we could also support something like this:

``` typescript
const transformation = {
 'keyinsource': 'keyintarget',
 'one': 'arraykey',
 'two': 'arraykey',
 'three': 'arraykey',
 'four': ['nested', 'key']
}
```

Which would transform

``` typescript
{
 'keyinsource':  'value',
 'one': 1,
 'two': 2,
 'three': 3,
 'four': 4
}
```

into

``` typescript
{
 'keintarget': 'value',
 'arraykey': [1, 2, 3],
 'nested': { 'key': 4 }
}
```

Which then could be internally transformed into a JSON Patch if needed.

> Functional - This should have full functional parity with the declarative syntax but be offered up in chain-able functions, so that a developer can build a transformation incrementally taking advantage of intellisense and robust type validation via TypeScript. There should also be a mechanism to serialise complete functional transformations into the declarative syntax.

I think a single function, that just performs the transformation itself, might be easier to than a chainable API, although that might be just because I can't currently think of what a good chainable API would look like. The nice thing about using JSON patch as the declarative format, or as one of the declarative formats, is that we already have a `diff` function to create a JSON patch between two objects for use elsewhere.

**Comment by maier49** [comment]
Transform API provided by #67
