### ISSUE TITLE
Update README with usage and implementation details

### ISSUE THREAD

**Issue by rishson** [dojo/stores#26]
Can we describe things such as:
- [ ] Do items have to be unique? 
- [ ] How are items determined to be unique?
- [ ] What is the big o expectations of insertion, deletion, retrieval, sorting?
- [ ] Are there any size constraints, e.g. max items and do we support rebasing if we break limits?

Will add to this list when I think of other things that I'd want to know when evaluating stores.

**Comment by maier49** [comment]
The readme sort of answers those questions about uniqueness in the section on the [store API](https://github.com/dojo/stores#store-1), but it could certainly stand to be clearer, and possibly pulled into its own section.

I'm not sure the performance questions should really be addressed in the readme, because the answers are a bit more complicated. All of the CRUD operations happen asynchronously, so the time before it returns is really indeterminate. If you do:

``` typescript
store.put().then(...)
// do something really slow and synchronous
```

You're not going to get the result back until after the synchronous operation finishes, regardless of how fast the internal implementation is. Obviously though that's not to say that performance isn't important.

The current default storage implementation is pretty straight forward, with something like O(1) insertions, O(1) updates(it keeps a map of IDs to indices),  and something like O(n) deletes, because it's updating the index after each delete, although the average would be much lower than that.

But adding queries into the mix makes things murkier. While the provided filters, range queries, and sorting do try to be performant, you could have any number of them and could provide custom ones as well. Querying is likely going to be used in most store use cases, so the default times might not matter much.

More importantly though, I think that we do want to make sure the store is performant, but its run time and ability to deal with huge amounts of data isn't really the main focus point. Often times people will be using a request store of some form to deal with data on a server, in which case the network will be the biggest bottleneck. If huge amounts of data need to be dealt with locally, that's probably something that would be better served by creating an implementation of `Storage`(the interface that deals with the actual CRUD operations) that hooks into an existing technology designed for dealing with that, rather than trying to overly tune the default in memory storage implementation. Although it should still be able to deal with a reasonably large amount of data out of the box! dstore provides the ability to hook into things like IndexedDB and LocalStorage, and we will probably want to follow suit as we build on stores. The focus of the library, and what I think we should emphasize in our docs, is its feature rich, composable API that provides the tools for dealing with data in the context of an application(e.g. observation, querying, transformation), and the consistency of that API across different storage mechanisms that can be chosen to meet the specific needs of an application.

**Comment by agubler** [comment]
Closing since the latest version of stores has landed
