### ISSUE TITLE
Store observables to execute immediately on subscription

### ISSUE THREAD

**Issue by agubler** [dojo/stores#58]
On subscription to the a store should fire immediately with the current state(?)

**Comment by maier49** [comment]
There are a couple reasons why this isn't happening at the moment. 

The first is because, in order to do this the observable would presumably need to have two possible types for the `onNext` callback. The first type would only ever be used once, but anybody subscribing to the store would have to handle both. It seems calling `fetch()` first might be more straightforward than adding logic to handle both types anywhere you observe the store.

The other reason is just the fact that if somebody wants to observe the store but doesn't need the initial data they're now forced into making a potentially more expensive request that they don't need. I'm not sure how many use cases there would be for observing the store without getting the initial state though so this probably isn't as big of a concern.

**Comment by maier49** [comment]
Potentially the first update could just use the existing `StoreDelta` structure, and list all of the items under the `adds` section. Which would eliminate the concerns about the parameter type.

**Comment by agubler** [comment]
@maier49 that is exactly what I think i'd expect as a consumer.
